### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Fratorec** [Fratorec/homepage#4]
Wants
Выковать кольцо Всевластия
Намайнить последний биткоин

DISLIKES
Неожиданные обновления

Образование
Родился от развращенности и спеси древней цивилизации. Когда человеческая империя достигла зенита, люди погрязли в моральном разложении.  В Имматериуме отражения их невоздержанности заставили пробудиться новую силу Хаоса. Первые частички кота, порождённые абсолютным потворством людей любым своим капризам, начали сплетаться воедино.

News 
Nyan Cat is being sold as a one-of-a-kind piece of crypto art
https://www.theverge.com/2021/2/18/22287956/nyan-cat-crypto-art-foundation-nft-sale-chris-torres
Why an Animated Flying Cat With a Pop-Tart Body Sold for Almost $600,000
https://www.nytimes.com/2021/02/22/business/nft-nba-top-shot-crypto.html

Языки LANGUAGES
Латынь Коптский Мэнский

**Comment by matviyukivan12** [comment]
Nice work!

**Comment by Fratorec** [comment]
Оставлю тут дубль
Wants
Выковать кольцо Всевластия
Намайнить последний биткоин

DISLIKES
Неожиданные обновления

Образование
Родился от развращенности и спеси древней цивилизации. Когда человеческая империя достигла зенита, люди погрязли в моральном разложении. В Имматериуме отражения их невоздержанности заставили пробудиться новую силу Хаоса. Первые частички кота, порождённые абсолютным потворством людей любым своим капризам, начали сплетаться воедино.

News
Nyan Cat is being sold as a one-of-a-kind piece of crypto art
https://www.theverge.com/2021/2/18/22287956/nyan-cat-crypto-art-foundation-nft-sale-chris-torres
Why an Animated Flying Cat With a Pop-Tart Body Sold for Almost $600,000
https://www.nytimes.com/2021/02/22/business/nft-nba-top-shot-crypto.html

Языки LANGUAGES
Латынь Коптский Мэнский
