### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Fratorec** [Fratorec/homepage#5]
2020
Вызвал обвал цен на рынке видеокарт. Также вместе с Илоном начал подогревать интерес к ранее бессмысленному Dogecoin.

2012
Во время церемонии награждения Оскар разрешил Тому Крузу вручать награду за лучший фильм. Это решение далось нелегко, но Том Круз тогда смотрелся лучше.

2010
Переименовал Kickstarter, сделав «s» прописной (ранее KickStarter). 

2005
Вместе с Трампом начал свою карьеру в компании его отца (Elizabeth Trump & Son).

1998
Уговорил Трампа развестись с его второй женой.

1981
Предложил комплектовать Xerox 8010 полусферической мышкой. Через несколько лет безвозмездно передал Стиву свою разработку.

1968
Понимая, что точечные транзисторы ведут в никуда, вместе с Робертом Нойсом и Гордоном Муром основал NM Electronics.

1947
Вместе с Уолтером Браттейном собрал первый работоспособный точечный транзистор. Успешно выпускал его на протяжении следующих 10 лет.

1212
Был одним из организаторов и координаторов Крестового похода детей. Я смог договориться с Алжирскими работорговцами о весьма выгодной сделке.

**Comment by matviyukivan12** [comment]
Nice work!

**Comment by Fratorec** [comment]
Что мне остается, кроме как продублировать текст...(
2020
Вызвал обвал цен на рынке видеокарт. Также вместе с Илоном начал подогревать интерес к ранее бессмысленному Dogecoin.

2012
Во время церемонии награждения Оскар разрешил Тому Крузу вручать награду за лучший фильм. Это решение далось нелегко, но Том Круз тогда смотрелся лучше.

2010
Переименовал Kickstarter, сделав «s» прописной (ранее KickStarter).

2005
Вместе с Трампом начал свою карьеру в компании его отца (Elizabeth Trump & Son).

1998
Уговорил Трампа развестись с его второй женой.

1981
Предложил комплектовать Xerox 8010 полусферической мышкой. Через несколько лет безвозмездно передал Стиву свою разработку.

1968
Понимая, что точечные транзисторы ведут в никуда, вместе с Робертом Нойсом и Гордоном Муром основал NM Electronics.

1947
Вместе с Уолтером Браттейном собрал первый работоспособный точечный транзистор. Успешно выпускал его на протяжении следующих 10 лет.

1212
Был одним из организаторов и координаторов Крестового похода детей. Я смог договориться с Алжирскими работорговцами о весьма выгодной сделке.
