### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Fratorec** [Fratorec/homepage#7]
Быть котом в такие времена – значит быть одним из бесчисленных миллиардов. Жить при самом жестоком и кровавом режиме, какой только можно вообразить. Вот уже более ста веков Император недвижимо восседает на Золотом Троне Терры. Он Повелитель Человечества и правит миллионом миров благодаря мощи своих неисчислимых армий. И перед вами история о коте с хвостом из радуги. Если вы достаточно безумны и вам нужен кто-то особенный, вы пришли по правильному адресу.

**Comment by matviyukivan12** [comment]
Nice work!

**Comment by Fratorec** [comment]
Что мне остается, кроме как продублировать текст...(
Быть котом в такие времена – значит быть одним из бесчисленных миллиардов. Жить при самом жестоком и кровавом режиме, какой только можно вообразить. Вот уже более ста веков Император недвижимо восседает на Золотом Троне Терры. Он Повелитель Человечества и правит миллионом миров благодаря мощи своих неисчислимых армий. И перед вами история о коте с хвостом из радуги. Если вы достаточно безумны и вам нужен кто-то особенный, вы пришли по правильному адресу.
